spring.application.name=multimessenger

spring.datasource.url=jdbc:mysql://localhost:3306/multimessenger
spring.datasource.username=root
spring.datasource.password=#VaTs9505Al
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
telegram.bot.token=dummy_token
discord.bot.token=dummy_token
